services:
  web:
    build: .
    container_name: procurai-backend
    
    # --- ADICIONE ESTA LINHA ---
    # Força o Docker a usar o servidor de desenvolvimento, que
    # obedece à regra static() do urls.py
    command: python manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/app
      # --- ADICIONE ESTA LINHA ---
      # Mapeia a pasta 'media' do seu PC para dentro do container
      - ./media:/app/media 
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      procurai-network:
        aliases:
          - web

  db:
    # (Seu serviço 'db' está perfeito, não mude nada)
    image: postgres:16-alpine
    container_name: procurai-database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      procurai-network:
        aliases:
          - db

volumes:
  db_data:

networks:
  procurai-network:
    driver: bridge